### ISSUE TITLE
ERROR   : 'DataFrame' object has no attribute '_data' and or ERROR   : maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by T-Man-Stan** [NREL/dgen#15]
Issue overview
--------------
This issue is likely caused by different versions of pandas used to make the agent files and to read them. It is likely specific to the residential agents. Updating to pandas 1.1.5 will probably resolve this issue. I will test and confirm

```
ERROR   : 'DataFrame' object has no attribute '_data'
Traceback (most recent call last):
  File "/Users/tstanley/Desktop/dgen/dgen_os/python/dgen_model.py", line 105, in main
    solar_agents = iFuncs.import_agent_file(scenario_settings, con, cur, engine, model_settings, agent_file_status, input_name='agent_file')
  File "/Users/tstanley/Desktop/dgen/dgen_os/python/input_data_functions.py", line 419, in import_agent_file
    solar_agents_df = solar_agents_df[solar_agents_df['state_abbr'].isin(state_to_model)]
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/frame.py", line 2773, in __getitem__
    if self.columns.is_unique and key in self.columns:
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas/_libs/properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute '_data'
```

and or

```
ERROR   : maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/Users/tstanley/Desktop/dgen/dgen_os/python/dgen_model.py", line 105, in main
    solar_agents = iFuncs.import_agent_file(scenario_settings, con, cur, engine, model_settings, agent_file_status, input_name='agent_file')
  File "/Users/tstanley/Desktop/dgen/dgen_os/python/input_data_functions.py", line 421, in import_agent_file
    if solar_agents_df.empty:
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5272, in __getattr__
    if self._info_axis._can_hold_identifiers_and_holds_name(name):
  [Previous line repeated 1471 more times]
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 493, in _info_axis
    return getattr(self, self._info_axis_name)
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "pandas/_libs/properties.pyx", line 63, in pandas._libs.properties.AxisProperty.__get__
  File "/Users/tstanley/opt/anaconda3/envs/dg3n/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by T-Man-Stan** [comment]
Resolved. Updated agent files saved with pandas==1.1.5 are now in OEDI.
