### ISSUE TITLE
Model does not work with copy_expert (copy_from no longer working due to psycopg2.9.*)

### ISSUE THREAD

**Issue by BT-VoteSolar** [NREL/dgen#30]
I am using the most recent (aka only) released files from dgen. By running the dgen model without any initial changes, the copy_from error pops up. Based on closed issue #25 I changed the copy_from line to:

cursor.copy_expert("COPY sql FROM STDIN",s)

This was changed in the excel_objects.py file. Below is the error that occurred. Seems like the program does not recognize that "sql" is a table. Is there an updated excel objects.py file to reflect that psycopg2.9.* is being used? Or, is there a set of lines for me to write to solve this error? Note: the data_objects.py file also has the copy_from line. This file will need updating as well.

INFO-8:Connected to Postgres with the following params:
{
    "dbname": "dgen_db",
    "host": "localhost",
    "port": "5432",
    "user": "postgres"
}
INFO-8:============================================
INFO-8:============================================
INFO-8:Running Scenario 1 of 1
INFO-8:-------------Preparing Database-------------
INFO-8:Creating output schema based on diffusion_template
INFO-8:	Output schema is: diffusion_results_20230103_150429564979_fina
INFO-8:	create_output_schema completed in: 4.54 seconds
INFO-8:Pool recreating
ERROR-8:	Loading failed with the following error: relation "sql" does not exist
Traceback (most recent call last):
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/settings.py", line 515, in init_scenario_settings
    excel_functions.load_scenario(scenario_settings.input_scenario, scenario_settings.schema, con, cur)
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/decorators.py", line 41, in function_timer
    result = f(*args, **kwargs)
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/excel/excel_functions.py", line 52, in load_scenario
    fnr.to_postgres(con,cur, schema, table)
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/excel/excel_objects.py", line 205, in to_postgres
    CREATE TABLE sql (id SERIAL PRIMARY KEY NOT NULL, origin VARCHAR NOT NULL, destination VARCHAR NOT NULL, duration INTEGER NOT NULL);
psycopg2.errors.UndefinedTable: relation "sql" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/dgen_model.py", line 75, in main
    scenario_settings = settings.init_scenario_settings(scenario_file, model_settings, con, cur)
  File "/Users/borathatan/Downloads/dgen/dgen_os/python/settings.py", line 517, in init_scenario_settings
    raise Exception('\tLoading failed with the following error: {}'.format(e))
Exception: 	Loading failed with the following error: relation "sql" does not exist

**Comment by BT-VoteSolar** [comment]
[dg_model.log](https://github.com/NREL/dgen/files/10339553/dg_model.log)
dg_model log file is attached.
